<a href="https://colab.research.google.com/github/biranchi2018/GAN-Examples/blob/master/InfoGAN_Latent_Points_Generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from numpy import hstack
from numpy.random import randn
from numpy.random import randint
from tensorflow.keras.utils import to_categorical

In [18]:
randn(10)

array([ 0.47872265, -0.70333033, -2.29800978,  0.94215841,  2.09138846,
        0.74047489, -1.41104412, -0.39485207, -1.12912853, -1.55466875])

In [19]:
randint(0, 5, 10)

array([4, 2, 0, 1, 2, 0, 4, 3, 4, 2])

In [28]:
to_categorical(2, num_classes=3)

array([0., 0., 1.], dtype=float32)

In [29]:
to_categorical(3, num_classes=5)

array([0., 0., 0., 1., 0.], dtype=float32)

In [30]:
to_categorical(4, num_classes=10)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [23]:
to_categorical([1,2,4], num_classes=5)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [0]:
def generate_latent_points(latent_dim, n_cat, n_samples):
  z_latent = randn(latent_dim * n_samples)
  z_latent = z_latent.reshape(n_samples, latent_dim)
  print(f"z_latent : {z_latent}")
  print(f"z_latent.shape : {z_latent.shape}")
  print()

  cat_codes = randint(0, n_cat, n_samples)
  print(f"cat_codes 1 : {cat_codes}")
  cat_codes = to_categorical(cat_codes, num_classes=n_cat)
  print(f"cat_codes 2 : {cat_codes}")
  print(f"cat_codes 2 shape : {cat_codes.shape}")
  print()

  z_input = hstack((z_latent, cat_codes))
  print(f"z_input : {z_input}")
  print(f"z_input.shape : {z_input.shape}")
  print()

  return [z_input, cat_codes]


In [27]:
latent_dim = 3
n_cat = 5
n_samples = 10

res = generate_latent_points(latent_dim, n_cat, n_samples)
res

z_latent : [[-1.5502632   1.0697119  -0.56613822]
 [-0.97865478 -1.29747266 -3.02996928]
 [ 0.37352081  0.00553882  0.08623125]
 [-0.72115102 -0.21971724  0.68800595]
 [ 0.52197912  0.17394182 -0.05345667]
 [-0.52279281 -0.00496928  1.10734087]
 [ 1.15924646 -1.18683381 -0.12085399]
 [-1.03084897 -0.43948865  0.72350595]
 [-2.13523905  0.21595425 -0.47578485]
 [ 0.90188089 -1.12719666  0.10884608]]
z_latent.shape : (10, 3)

cat_codes 1 : [4 1 4 1 3 1 3 2 1 2]
cat_codes 2 : [[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
cat_codes 2 shape : (10, 5)

z_input : [[-1.5502632   1.0697119  -0.56613822  0.          0.          0.
   0.          1.        ]
 [-0.97865478 -1.29747266 -3.02996928  0.          1.          0.
   0.          0.        ]
 [ 0.37352081  0.00553882  0.08623125  0.          0.          0.
   0.          1.        ]
 [-0.72115102 -0.219717

[array([[-1.5502632 ,  1.0697119 , -0.56613822,  0.        ,  0.        ,
          0.        ,  0.        ,  1.        ],
        [-0.97865478, -1.29747266, -3.02996928,  0.        ,  1.        ,
          0.        ,  0.        ,  0.        ],
        [ 0.37352081,  0.00553882,  0.08623125,  0.        ,  0.        ,
          0.        ,  0.        ,  1.        ],
        [-0.72115102, -0.21971724,  0.68800595,  0.        ,  1.        ,
          0.        ,  0.        ,  0.        ],
        [ 0.52197912,  0.17394182, -0.05345667,  0.        ,  0.        ,
          0.        ,  1.        ,  0.        ],
        [-0.52279281, -0.00496928,  1.10734087,  0.        ,  1.        ,
          0.        ,  0.        ,  0.        ],
        [ 1.15924646, -1.18683381, -0.12085399,  0.        ,  0.        ,
          0.        ,  1.        ,  0.        ],
        [-1.03084897, -0.43948865,  0.72350595,  0.        ,  0.        ,
          1.        ,  0.        ,  0.        ],
        [-2.1352