<a href="https://colab.research.google.com/github/biranchi2018/GAN-Examples/blob/master/Numpy_Random_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## np.random.rand()

In [2]:
np.random.rand(2,3)

array([[0.20834618, 0.8298083 , 0.88923938],
       [0.00303549, 0.24503889, 0.04027847]])

## np.random.randint()

In [3]:
np.random.randint(2, size=10)

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 1])

In [4]:
np.random.randint(5, size=(2, 4))

array([[4, 4, 0, 1],
       [3, 1, 4, 3]])

## np.random.randn()

In [6]:
np.random.randn()

1.1466396302202666

In [7]:
np.random.randn(10)

array([-0.51611979, -0.64984341, -0.2436996 ,  2.03495572, -0.39989393,
       -0.0573103 , -0.77814435,  1.4475503 , -0.02372563,  0.0554169 ])

In [11]:
np.random.randn(2,4)

array([[-1.35087498,  0.72463598, -1.30786728,  0.41531134],
       [ 0.14395481,  1.38525168, -0.50627384,  0.81525889]])

## np.random.random()

In [9]:
np.random.random()

0.033151212867141844

In [10]:
np.random.random(10)

array([0.10204965, 0.13285584, 0.04365701, 0.18526555, 0.12830414,
       0.92079558, 0.00437568, 0.2986847 , 0.64630114, 0.0502897 ])

## np.random.uniform()

In [12]:
np.random.uniform(-1,0,10)

array([-0.75829766, -0.65317797, -0.54024525, -0.47801858, -0.25121814,
       -0.59445174, -0.32798031, -0.2345569 , -0.80991428, -0.53212396])

In [17]:
np.random.uniform(2,6, 20)

array([3.78101896, 5.40123573, 5.52673127, 3.61979044, 2.0289945 ,
       2.18054617, 2.25586661, 5.765981  , 5.49992522, 2.84924954,
       2.98594223, 5.2745376 , 2.39422534, 3.40092313, 4.41528841,
       2.21020611, 5.65377855, 2.40679451, 4.70655818, 4.16687239])